import 'dart:io';

import 'package:easy_callers_mobile/features/employee/controllers/call_controller.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:easy_callers_mobile/features/manager/models/lead_model.dart';
import 'package:easy_callers_mobile/features/employee/models/call_log_model.dart';
import 'package:easy_callers_mobile/features/manager/services/lead_service.dart';
import 'package:easy_callers_mobile/core/services/auth_service.dart';
import 'package:easy_callers_mobile/core/utils/enums.dart';

import 'package:easy_callers_mobile/features/employee/models/lead_status_model.dart';
import '../models/call_session_model.dart';

class LeadDetailController extends GetxController {
  // static const platform = MethodChannel('com.easy_callers/call');
  final LeadModel lead;
  final LeadService _leadService = Get.find<LeadService>();
  final AuthService _authService = Get.find<AuthService>();
  final Rx<CallSession?> lastCallSession = Rx<CallSession?>(null);
  LeadDetailController({required this.lead});

  final RxString selectedStatus = ''.obs;
  final RxList<LeadStatusModel> availableLeadStatuses = <LeadStatusModel>[].obs;
  final RxBool followUpEnabled = false.obs;
  final Rx<DateTime?> followUpDate = Rx<DateTime?>(null);
  final RxBool isLoading = false.obs;
  final RxInt callDurationSeconds = 0.obs;
  final TextEditingController notesController = TextEditingController();
  var callController = Get.find<CallController>();
  @override
  void onInit() {
    super.onInit();
    // Set initial status based on lead status
    selectedStatus.value = lead.status.value;
    fetchLeadStatuses();
  }

  Future<void> fetchLeadStatuses() async {
    try {
      final managerId = _authService.currentEmployee.value?.managerId;
      final statuses = await _leadService.getLeadStatuses(managerId);
      availableLeadStatuses.assignAll(statuses);
    } catch (e) {
      print('Error loading statuses: $e');
    }
  }

  @override
  void onClose() {
    notesController.dispose();
    super.onClose();
  }


  Future<void> makeCall() async {
    try {
      CallSession? session;

      if (Platform.isIOS) {
        session = await callController.makeCallForIos(
          phoneNumber: lead.phone,
        );
      } else {
        session = await callController.makeCall(
          phoneNumber: lead.phone,
        );
      }

      if (session == null) {
        selectedStatus.value = 'no_answer';
        callDurationSeconds.value = 0;
        lastCallSession.value = null;
        return;
      }

      lastCallSession.value = session;
      callDurationSeconds.value = session.durationInSeconds;
      // Save duration
      callDurationSeconds.value = session.durationInSeconds;

      // Business decision
      if (!session.isConnected) {
        selectedStatus.value = 'callback';
      } else if (session.durationInSeconds > 30) {
        selectedStatus.value = 'interested';
      } else {
        selectedStatus.value = 'callback';
      }

    } catch (e) {
      print("object $e");
      Get.snackbar("Error", "Call failed: $e");
    }
  }



  whatsappMsg() {
    if (Platform.isIOS) {
      callController.launchWhatsAppChatForIos(lead.phone);
    } else {
      callController.sendWhatsAppMessage([lead.phone], "Hello");
    }
  }

  sendMobileSMS(){
    if (Platform.isIOS) {
      callController.sendSMS(lead.phone,"Hello");
    } else {
      callController.sendSMS(lead.phone, "Hello");
    }
  }

  Future<void> saveUpdate() async {
    try {
      isLoading.value = true;

      final employeeId = _authService.currentEmployee.value?.id;
      if (employeeId == null) {
        Get.snackbar('Error', 'Employee not found');
        return;
      }

      final session = callController.callSession.value;
      // Create call log
      final callLog = CallLogModel(
        id: '', // Will be generated by database
        leadId: lead.id,
        employeeId: employeeId,
        callStatus: session?.status?? (lastCallSession.value?.status ?? 'Completed'),
        leadStatus: selectedStatus.value,
        callDurationSeconds: callDurationSeconds.value,
        feedback: notesController.text.trim().isNotEmpty 
            ? notesController.text.trim() 
            : null,
        followUpDate: followUpEnabled.value && followUpDate.value != null
            ? followUpDate.value
            : null,
        createdAt: DateTime.now(),
      );

      // Save call log
      final savedLog = await _leadService.addCallLog(callLog);

      if (savedLog != null) {
        Get.snackbar(
          'Success',
          'Call log saved successfully',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green.withOpacity(0.8),
          colorText: Colors.white,
        );

        // Go back to dashboard
        Get.back();
      } else {
        throw Exception('Failed to save call log');
      }
    } catch (e) {
      print("Fail $e");
      Get.snackbar(
        'Error',
        'Failed to save update: $e',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red.withOpacity(0.8),
        colorText: Colors.white,
      );
    } finally {
      isLoading.value = false;
    }
  }
}
