import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:easy_callers_mobile/features/manager/models/lead_model.dart';
import 'package:easy_callers_mobile/features/employee/models/call_log_model.dart';
import 'package:easy_callers_mobile/features/manager/services/lead_service.dart';
import 'package:easy_callers_mobile/core/services/auth_service.dart';
import 'package:easy_callers_mobile/core/utils/enums.dart';
import 'package:flutter/services.dart';

class LeadDetailController extends GetxController {
  static const platform = MethodChannel('com.easy_callers/call');
  final LeadModel lead;
  final LeadService _leadService = Get.find<LeadService>();
  final AuthService _authService = Get.find<AuthService>();

  LeadDetailController({required this.lead});

  final RxString selectedStatus = ''.obs;
  final RxBool followUpEnabled = false.obs;
  final Rx<DateTime?> followUpDate = Rx<DateTime?>(null);
  final RxBool isLoading = false.obs;
  final RxInt callDurationSeconds = 0.obs;
  final TextEditingController notesController = TextEditingController();

  @override
  void onInit() {
    super.onInit();
    // Set initial status based on lead status
    selectedStatus.value = lead.status.value;
  }

  @override
  void onClose() {
    notesController.dispose();
    super.onClose();
  }

  Future<void> makeCall() async {
    try {
      final dynamic result = await platform.invokeMethod('startCall', {
        'number': lead.phone,
      });
      
      if (result != null && result is Map) {
        final Map<dynamic, dynamic> callData = result;
        notesController.text = callData['display_string'] ?? '';
        
        final bool isConnected = callData['is_connected'] ?? false;
        final int duration = (callData['duration'] as num?)?.toInt() ?? 0;
        callDurationSeconds.value = duration;

        if (!isConnected) {
          // If call was declined or failed, auto-select "No Answer"
          selectedStatus.value = 'no_answer';
        } else {
          // If call was successful, check duration
          if (duration > 30) {
            selectedStatus.value = 'interested';
          } else if (selectedStatus.value == 'no_answer' || selectedStatus.value == '') {
            // If it was connected but short, at least move it away from "no_answer"
            selectedStatus.value = 'callback';
          }
        }
      }
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        Get.snackbar('Permission Denied', 'Please grant call permissions in settings');
      } else {
        Get.snackbar('Error', 'Failed to start call: ${e.message}');
      }
    }
  }

  Future<void> sendSMS() async {
    try {
      await platform.invokeMethod('sendSMS', {
        'number': lead.phone,
        'message': 'Hello ${lead.name}, ',
      });
    } on PlatformException catch (e) {
      Get.snackbar('Error', 'Failed to send SMS: ${e.message}');
    }
  }

  Future<void> whatsappCall() async {
    try {
      await platform.invokeMethod('whatsappCall', {
        'number': lead.phone,
      });
    } on PlatformException catch (e) {
      Get.snackbar('Error', 'Failed to start WhatsApp call: ${e.message}');
    }
  }

  Future<void> saveUpdate() async {
    try {
      isLoading.value = true;

      final employeeId = _authService.currentEmployee.value?.id;
      if (employeeId == null) {
        Get.snackbar('Error', 'Employee not found');
        return;
      }

      // Determine call status based on selected status
      CallStatus callStatus;
      CallLeadStatus? leadStatus;

      switch (selectedStatus.value) {
        case 'interested':
          callStatus = CallStatus.connected;
          leadStatus = CallLeadStatus.interested;
          break;
        case 'not_interested':
          callStatus = CallStatus.connected;
          leadStatus = CallLeadStatus.notInterested;
          break;
        case 'callback':
          callStatus = CallStatus.connected;
          leadStatus = CallLeadStatus.callback;
          break;
        case 'no_answer':
          callStatus = CallStatus.notConnected;
          leadStatus = null;
          break;
        default:
          callStatus = CallStatus.connected;
          leadStatus = null;
      }

      // Create call log
      final callLog = CallLogModel(
        id: '', // Will be generated by database
        leadId: lead.id,
        employeeId: employeeId,
        callStatus: callStatus,
        leadStatus: leadStatus,
        callDurationSeconds: callDurationSeconds.value,
        feedback: notesController.text.trim().isNotEmpty 
            ? notesController.text.trim() 
            : null,
        followUpDate: followUpEnabled.value && followUpDate.value != null
            ? followUpDate.value
            : null,
        createdAt: DateTime.now(),
      );

      // Save call log
      final savedLog = await _leadService.addCallLog(callLog);

      if (savedLog != null) {
        Get.snackbar(
          'Success',
          'Call log saved successfully',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green.withOpacity(0.8),
          colorText: Colors.white,
        );

        // Go back to dashboard
        Get.back();
      } else {
        throw Exception('Failed to save call log');
      }
    } catch (e) {
      print("Fail $e");
      Get.snackbar(
        'Error',
        'Failed to save update: $e',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red.withOpacity(0.8),
        colorText: Colors.white,
      );
    } finally {
      isLoading.value = false;
    }
  }
}
