import 'dart:async';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:easy_callers_mobile/core/models/employee_model.dart';
import 'package:easy_callers_mobile/core/services/lead_service.dart';
import 'package:easy_callers_mobile/core/services/auth_service.dart';

class ManagerTeamController extends GetxController {
  final LeadService _leadService = Get.find<LeadService>();
  final AuthService _authService = Get.find<AuthService>();

  final RxList<EmployeeModel> employees = <EmployeeModel>[].obs;
  final RxBool isLoading = false.obs;

  // Add Employee State
  final firstNameController = TextEditingController();
  final lastNameController = TextEditingController();
  final emailController = TextEditingController();
  final phoneController = TextEditingController();
  
  final RxString activeOTP = ''.obs;
  final RxInt otpExpiresIn = 300.obs; // 5 minutes
  final RxBool isCreating = false.obs;
  Timer? _otpTimer;

  @override
  void onInit() {
    super.onInit();
    fetchEmployees();
  }

  Future<void> fetchEmployees() async {
    try {
      isLoading.value = true;
      final managerId = _authService.currentManager.value?.id;
      if (managerId == null) return;

      final result = await _leadService.getEmployeesByManager(managerId);
      employees.value = result;
    } catch (e) {
      Get.snackbar('Error', 'Failed to fetch team: $e');
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> createEmployee() async {
    if (!_validateFields()) return;

    try {
      isCreating.value = true;
      final result = await _authService.createEmployee(
        email: emailController.text.trim(),
        firstName: firstNameController.text.trim(),
        lastName: lastNameController.text.trim(),
        phone: phoneController.text.trim().isEmpty ? null : phoneController.text.trim(),
      );

      if (result.employee != null) {
        activeOTP.value = result.otp!;
        _startOTPTimer();
        fetchEmployees(); // Refresh list
        Get.snackbar('Success', 'Employee created. Share the OTP below with them.');
        _clearFields(keepOTP: true);
      } else {
        Get.snackbar('Error', _authService.error.value);
      }
    } catch (e) {
      Get.snackbar('Error', 'Failed to create employee: $e');
    } finally {
      isCreating.value = false;
    }
  }

  bool _validateFields() {
    if (firstNameController.text.isEmpty || 
        lastNameController.text.isEmpty || 
        emailController.text.isEmpty) {
      Get.snackbar('Required', 'First name, last name, and email are required');
      return false;
    }
    return true;
  }

  void _clearFields({bool keepOTP = false}) {
    firstNameController.clear();
    lastNameController.clear();
    emailController.clear();
    phoneController.clear();
    if (!keepOTP) {
      activeOTP.value = '';
      _otpTimer?.cancel();
    }
  }

  void _startOTPTimer() {
    _otpTimer?.cancel();
    otpExpiresIn.value = 86400; // Match 24 hours from AuthService
    _otpTimer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (otpExpiresIn.value > 0) {
        otpExpiresIn.value--;
      } else {
        timer.cancel();
      }
    });
  }

  // Deprecated: OTP is now generated by AuthService
  void generateOTP() {}

  String get formattedTimer {
    final minutes = (otpExpiresIn.value ~/ 60).toString().padLeft(2, '0');
    final seconds = (otpExpiresIn.value % 60).toString().padLeft(2, '0');
    return '$minutes:$seconds';
  }

  @override
  void onClose() {
    _otpTimer?.cancel();
    firstNameController.dispose();
    lastNameController.dispose();
    emailController.dispose();
    phoneController.dispose();
    super.onClose();
  }
}
